include:
  - board: nice_nano
    shield: lily58_left
  - board: nice_nano
    shield: lily58_right
  - board: xiao_ble
    shield: lily58_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: settings_reset
